function bodyheight(){var HeaderHeight=$('#Header').height()
var RibbonHeight=$('#Ribbonrow').height()
var bodyheight=$('body').height()-HeaderHeight-RibbonHeight-$('#Footer').height()
var bodyheightmobile=$('body').height()-HeaderHeight-$('#Footer').height()
if($(window).width()>990){$('#MainContent').css({"min-height":bodyheight})}else{$('#MainContent').css({"min-height":bodyheightmobile})}}
function HeaderScroll(){var HeaderHeight=$('#Header').height()
var RibbonHeight=$('#Ribbonrow').height()
if($(window).width()>990){if($(window).scrollTop()>RibbonHeight){$('#Header').addClass('Fixed');$('#MainContent').css('padding-top',HeaderHeight)}else{$('#Header').removeClass('Fixed');$('#MainContent').css('padding-top','0')}}}
function NavTabs(){if($(window).width()>990){$(function(){$('.ExpertiseTabs .tab-wrapper a').on('mouseenter',function(){show_content($(this).index())});show_content(0);function show_content(index){$('.ExpertiseTabs .content.visible').removeClass('visible');$('.ExpertiseTabs .content:nth-of-type('+(index+1)+')').addClass('visible');$('.ExpertiseTabs .tab-wrapper a.selected').removeClass('selected');$('.ExpertiseTabs .tab-wrapper a:nth-of-type('+(index+1)+')').addClass('selected')}});$(function(){$('.ServicesTabs .tab-wrapper a').on('mouseenter',function(){show_content($(this).index())});show_content(0);function show_content(index){$('.ServicesTabs .content.visible').removeClass('visible');$('.ServicesTabs .content:nth-of-type('+(index+1)+')').addClass('visible');$('.ServicesTabs .tab-wrapper a.selected').removeClass('selected');$('.ServicesTabs .tab-wrapper a:nth-of-type('+(index+1)+')').addClass('selected')}});$(function(){$('.ProductsTabs .tab-wrapper a').on('mouseenter',function(){show_content($(this).index())});show_content(0);function show_content(index){$('.ProductsTabs .content.visible').removeClass('visible');$('.ProductsTabs .content:nth-of-type('+(index+1)+')').addClass('visible');$('.ProductsTabs .tab-wrapper a.selected').removeClass('selected');$('.ProductsTabs .tab-wrapper a:nth-of-type('+(index+1)+')').addClass('selected')}});$(function(){$('.AboutTabs .tab-wrapper a').on('mouseenter',function(){show_content($(this).index())});show_content(0);function show_content(index){$('.AboutTabs .content.visible').removeClass('visible');$('.AboutTabs .content:nth-of-type('+(index+1)+')').addClass('visible');$('.AboutTabs .tab-wrapper a.selected').removeClass('selected');$('.AboutTabs .tab-wrapper a:nth-of-type('+(index+1)+')').addClass('selected')}})}else{$('.ExpertiseTabs .content.visible').removeClass('visible');$('.ExpertiseTabs .tab-wrapper a.selected').removeClass('selected');$('.ServicesTabs .content.visible').removeClass('visible');$('.ServicesTabs .tab-wrapper a.selected').removeClass('selected');$('.ProductsTabs .content.visible').removeClass('visible');$('.ProductsTabs rtiseTabs .tab-wrapper a.selected').removeClass('selected');$('.AboutTabs .content.visible').removeClass('visible');$('.AboutTabs .tab-wrapper a.selected').removeClass('selected');$(function(){$('.ExpertiseTabs .tab-wrapper a.dropdown').on('click',function(e){e.preventDefault()
show_content($(this).index())});function show_content(index){$('.ExpertiseTabs .content.visible').removeClass('visible');$('.ExpertiseTabs .content:nth-of-type('+(index+1)+')').addClass('visible');$('.ExpertiseTabs .tab-wrapper a.selected').removeClass('selected');$('.ExpertiseTabs .tab-wrapper a:nth-of-type('+(index+1)+')').addClass('selected');$('.expertise-dropdown-inner').addClass('Hidden')}});$(function(){$('.ServicesTabs .tab-wrapper a.dropdown').on('click',function(e){e.preventDefault()
show_content($(this).index())});function show_content(index){$('.ServicesTabs .content.visible').removeClass('visible');$('.ServicesTabs .content:nth-of-type('+(index+1)+')').addClass('visible');$('.ServicesTabs .tab-wrapper a.selected').removeClass('selected');$('.ServicesTabs .tab-wrapper a:nth-of-type('+(index+1)+')').addClass('selected');$('.services-dropdown-inner').addClass('Hidden')}});$(function(){$('.ProductsTabs .tab-wrapper a.dropdown').on('click',function(e){e.preventDefault()
show_content($(this).index())});function show_content(index){$('.ProductsTabs .content.visible').removeClass('visible');$('.ProductsTabs .content:nth-of-type('+(index+1)+')').addClass('visible');$('.ProductsTabs .tab-wrapper a.selected').removeClass('selected');$('.ProductsTabs .tab-wrapper a:nth-of-type('+(index+1)+')').addClass('selected');$('.products-dropdown-inner').addClass('Hidden')}});$(function(){$('.AboutTabs .tab-wrapper a.dropdown').on('click',function(e){e.preventDefault()
show_content($(this).index())});function show_content(index){$('.AboutTabs .content.visible').removeClass('visible');$('.AboutTabs .content:nth-of-type('+(index+1)+')').addClass('visible');$('.AboutTabs .tab-wrapper a.selected').removeClass('selected');$('.AboutTabs .tab-wrapper a:nth-of-type('+(index+1)+')').addClass('selected');$('.about-dropdown-inner').addClass('Hidden')}});$(".ExpertiseTabs .SecondLevel-MobileBack").click(function(){$('.ExpertiseTabs .content.visible').removeClass('visible');$('.ExpertiseTabs .tab-wrapper a.selected').removeClass('selected');$('.expertise-dropdown-inner').removeClass('Hidden')});$(".ServicesTabs .SecondLevel-MobileBack").click(function(){$('.ServicesTabs .content.visible').removeClass('visible');$('.ServicesTabs .tab-wrapper a.selected').removeClass('selected');$('.services-dropdown-inner').removeClass('Hidden')});$(".ProductsTabs .SecondLevel-MobileBack").click(function(){$('.ProductsTabs .content.visible').removeClass('visible');$('.ProductsTabs .tab-wrapper a.selected').removeClass('selected');$('.products-dropdown-inner').removeClass('Hidden')});$(".AboutTabs .SecondLevel-MobileBack").click(function(){$('.AboutTabs .content.visible').removeClass('visible');$('.AboutTabs .tab-wrapper a.selected').removeClass('selected');$('.about-dropdown-inner').removeClass('Hidden')})}}
$(".MobileBack").click(function(){$(".dropdown-menu").removeClass('show')});$(".dropdown-menu").click(function(e){e.stopPropagation()});$(function(){$('.nav-item .nav-link').each(function(){if($(this).prop('href')==window.location.href){$(this).addClass('current')}})});function Loader(){$('#OverlayLoader').delay(500).fadeOut()}
function MiniDropdown(){ $("#MainContent").click(function () { if ($(".support-dropdown .dropdown-content").hasClass('show')) { $(".support-dropdown-button").removeClass('show'); $(".support-dropdown .dropdown-content").removeClass('show'); } }); $(".support-dropdown-button").click(function () { $(this).toggleClass('show'); $(".support-dropdown .dropdown-content").toggleClass('show') });}
$(document).ready(function(){bodyheight(),NavTabs(),MiniDropdown()}),$(window).resize(function(){bodyheight(),HeaderScroll(),NavTabs()}),$(window).load(function(){Loader()}),$(window).scroll(function(){HeaderScroll()})